### ISSUE TITLE
Meta-issue: recurrent compatibility lag

### ISSUE THREAD

**Issue by rulatir** [EmmyLua/IntelliJ-EmmyLua#348] opened 2020-04-16 07:39 UTC
Why is this plugin ALWAYS incompatible right after a new PHPStorm release drops? Is there no release candidate cycle that exists, among other things, to allow plugin authors a time window to upgrade their plugins?

**Comment by tangzx** [comment] 2020-04-19 01:28
Duplicate of #340

**Closed by tangzx** 2020-04-19 01:28 UTC
